---
- name: Echo "I am running" on all servers
  gather_facts: no
  hosts: localhost

  tasks:
    - name: Echo "I am running"
      ansible.builtin.shell: echo "I am running"


# ---
# - name: Ping all servers
#   hosts: servers
#   gather_facts: no

#   tasks:
#     - name: Ping the server
#       ansible.builtin.ping:
