---
- name: Test localhost connection
  gather_facts: no
  hosts: localhost
  connection: local

  tasks:
    - name: Print a debug message
      ansible.builtin.debug:
        msg: "I am running, this message is from GITHUB and from Specific BRANCH"
